version: "3.9"

services:
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception_network

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file: .env
    environment:
      - DB_CONF_ROUTE=/etc/mysql/mariadb.conf.d/50-server.cnf
      - DB_INSTALL=/var/lib/mysql
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
  mariadb_data:
    name: mariadb_data